Updating R CMD check Actions
poissonconsulting/mbr pull request #30
Opened 2021-11-10 19:07 UTC by MowahidLatif

Do not merge as of yet, pending action results and comparing from previous errors

2021-11-10 19:28 UTC, MowahidLatif commented
Please merge this branch. Everything is in order.

2021-11-11 23:11 UTC, aylapear requested changes
Please correct the badges. Switch R-CMD-check for the R build status badge.

Looks good otherwise.

2021-11-12 20:23 UTC, MowahidLatif commented
Please merge this branch. Everything is in order.

2021-11-12 23:06 UTC, aylapear approved these changes

2021-11-12 23:06 UTC, merged